Attempt to bump vulkano to 0.22.0 but failed
```
thread 'main' panicked at 'Failed to execute command buffer: AccessError { error: ExclusiveDenied, command_name: "vkCmdBindDescriptorSets", command_param: "Buffer bound to descriptor 0 of set 1", command_offset: 34 }', src/bin/fbx-viewer/vulkan.rs:346:22
```

Note that THIS DEMO APPLICATION IS NO LONGER MAINTAINED... Read README.